version: '3.8'

services:
  auth:
    container_name: node_auth
    restart: unless-stopped
    build:
      context: ./auth
    volumes:
      - .:/app
    networks:
      - node
#  recommendations:
#    container_name: node_recommendations
#    restart: unless-stopped
#    build:
#      context: ./recommendations
#    volumes:
#      - .:/app
#    networks:
#      - node
#  tours:
#    container_name: node_tours
#    restart: unless-stopped
#    build:
#      context: ./tours
#    volumes:
#      - .:/app
#    networks:
#      - node

  postgres:
    container_name: node_postgres
    restart: unless-stopped
    image: postgres:14
    ports:
      - "5432:5432"
    env_file:
      - ./pgsql/.env
    volumes:
      - node-pgsql-volume:/var/lib/postgresql/data
    networks:
      - node

networks:
  node:
    driver: bridge

volumes:
  node-pgsql-volume:
    driver: local